### PR TITLE
Add fix for changing POST to GET request

### LINKED ISSUE #11: Modify get_reserved.php to be a GET call instead of a POST call
Modify get_reserved.php to be a GET call instead of a POST call.

### PR DESCRIPTION
**Pull request by mihi-r**
Add fix for changing POST to GET request. 

#11.

### CODE REVIEW

File: api/get_reserved.php [hunk 1]
```diff
@@ -11,9 +11,9 @@
 $monthList = "";
 $yearList = "";
 
-$dateList = mysqli_real_escape_string($mysqli, strip_tags(trim($_POST["dateListText"])));
-$monthList = mysqli_real_escape_string($mysqli, strip_tags(trim($_POST["monthListText"])));
-$yearList = mysqli_real_escape_string($mysqli, strip_tags(trim($_POST["yearListText"])));
+$dateList = mysqli_real_escape_string($mysqli, strip_tags(trim($_GET["dateListText"])));
```
Comment (KaaiiH) [inline api/get_reserved.php:14]: This is a comment I'm trying to make

**Review by huber2jb — APPROVED** [review]
